/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as BreakingRouteImport } from './routes/breaking'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as EditionsRouteImport } from './routes/editions'
import { Route as ParishRouteImport } from './routes/parish'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as SundayRouteImport } from './routes/sunday'
import { Route as VillageRouteImport } from './routes/village'
import { Route as ApiCalendarDoticsRouteImport } from './routes/api/calendar[.]ics'
import { Route as DispatchesIndexRouteImport } from './routes/dispatches.index'
import { Route as DispatchesSlugRouteImport } from './routes/dispatches.$slug'
import { Route as EditionDateRouteImport } from './routes/edition.$date'
import { Route as ApiEventsIdDoticsRouteImport } from './routes/api/events/$id[.]ics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakingRoute = BreakingRouteImport.update({
  id: '/breaking',
  path: '/breaking',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsRoute = EditionsRouteImport.update({
  id: '/editions',
  path: '/editions',
  getParentRoute: () => rootRouteImport,
} as any)
const ParishRoute = ParishRouteImport.update({
  id: '/parish',
  path: '/parish',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SundayRoute = SundayRouteImport.update({
  id: '/sunday',
  path: '/sunday',
  getParentRoute: () => rootRouteImport,
} as any)
const VillageRoute = VillageRouteImport.update({
  id: '/village',
  path: '/village',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarDoticsRoute = ApiCalendarDoticsRouteImport.update({
  id: '/api/calendar.ics',
  path: '/api/calendar.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchesIndexRoute = DispatchesIndexRouteImport.update({
  id: '/dispatches/',
  path: '/dispatches/',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchesSlugRoute = DispatchesSlugRouteImport.update({
  id: '/dispatches/$slug',
  path: '/dispatches/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionDateRoute = EditionDateRouteImport.update({
  id: '/edition/$date',
  path: '/edition/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIdDoticsRoute = ApiEventsIdDoticsRouteImport.update({
  id: '/api/events/$id.ics',
  path: '/api/events/$id.ics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/breaking': typeof BreakingRoute
  '/calendar': typeof CalendarRoute
  '/editions': typeof EditionsRoute
  '/parish': typeof ParishRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/subscribe': typeof SubscribeRoute
  '/sunday': typeof SundayRoute
  '/village': typeof VillageRoute
  '/api/calendar.ics': typeof ApiCalendarDoticsRoute
  '/dispatches/$slug': typeof DispatchesSlugRoute
  '/edition/$date': typeof EditionDateRoute
  '/dispatches/': typeof DispatchesIndexRoute
  '/api/events/$id.ics': typeof ApiEventsIdDoticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/breaking': typeof BreakingRoute
  '/calendar': typeof CalendarRoute
  '/editions': typeof EditionsRoute
  '/parish': typeof ParishRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/subscribe': typeof SubscribeRoute
  '/sunday': typeof SundayRoute
  '/village': typeof VillageRoute
  '/api/calendar.ics': typeof ApiCalendarDoticsRoute
  '/dispatches/$slug': typeof DispatchesSlugRoute
  '/edition/$date': typeof EditionDateRoute
  '/dispatches': typeof DispatchesIndexRoute
  '/api/events/$id.ics': typeof ApiEventsIdDoticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/breaking': typeof BreakingRoute
  '/calendar': typeof CalendarRoute
  '/editions': typeof EditionsRoute
  '/parish': typeof ParishRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/subscribe': typeof SubscribeRoute
  '/sunday': typeof SundayRoute
  '/village': typeof VillageRoute
  '/api/calendar.ics': typeof ApiCalendarDoticsRoute
  '/dispatches/$slug': typeof DispatchesSlugRoute
  '/edition/$date': typeof EditionDateRoute
  '/dispatches/': typeof DispatchesIndexRoute
  '/api/events/$id.ics': typeof ApiEventsIdDoticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/advertise'
    | '/breaking'
    | '/calendar'
    | '/editions'
    | '/parish'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sports'
    | '/subscribe'
    | '/sunday'
    | '/village'
    | '/api/calendar.ics'
    | '/dispatches/$slug'
    | '/edition/$date'
    | '/dispatches/'
    | '/api/events/$id.ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/advertise'
    | '/breaking'
    | '/calendar'
    | '/editions'
    | '/parish'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sports'
    | '/subscribe'
    | '/sunday'
    | '/village'
    | '/api/calendar.ics'
    | '/dispatches/$slug'
    | '/edition/$date'
    | '/dispatches'
    | '/api/events/$id.ics'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/advertise'
    | '/breaking'
    | '/calendar'
    | '/editions'
    | '/parish'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sports'
    | '/subscribe'
    | '/sunday'
    | '/village'
    | '/api/calendar.ics'
    | '/dispatches/$slug'
    | '/edition/$date'
    | '/dispatches/'
    | '/api/events/$id.ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AdvertiseRoute: typeof AdvertiseRoute
  BreakingRoute: typeof BreakingRoute
  CalendarRoute: typeof CalendarRoute
  EditionsRoute: typeof EditionsRoute
  ParishRoute: typeof ParishRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsRoute: typeof SportsRoute
  SubscribeRoute: typeof SubscribeRoute
  SundayRoute: typeof SundayRoute
  VillageRoute: typeof VillageRoute
  ApiCalendarDoticsRoute: typeof ApiCalendarDoticsRoute
  DispatchesSlugRoute: typeof DispatchesSlugRoute
  EditionDateRoute: typeof EditionDateRoute
  DispatchesIndexRoute: typeof DispatchesIndexRoute
  ApiEventsIdDoticsRoute: typeof ApiEventsIdDoticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breaking': {
      id: '/breaking'
      path: '/breaking'
      fullPath: '/breaking'
      preLoaderRoute: typeof BreakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions': {
      id: '/editions'
      path: '/editions'
      fullPath: '/editions'
      preLoaderRoute: typeof EditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parish': {
      id: '/parish'
      path: '/parish'
      fullPath: '/parish'
      preLoaderRoute: typeof ParishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sunday': {
      id: '/sunday'
      path: '/sunday'
      fullPath: '/sunday'
      preLoaderRoute: typeof SundayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/village': {
      id: '/village'
      path: '/village'
      fullPath: '/village'
      preLoaderRoute: typeof VillageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar.ics': {
      id: '/api/calendar.ics'
      path: '/api/calendar.ics'
      fullPath: '/api/calendar.ics'
      preLoaderRoute: typeof ApiCalendarDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatches/': {
      id: '/dispatches/'
      path: '/dispatches'
      fullPath: '/dispatches/'
      preLoaderRoute: typeof DispatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatches/$slug': {
      id: '/dispatches/$slug'
      path: '/dispatches/$slug'
      fullPath: '/dispatches/$slug'
      preLoaderRoute: typeof DispatchesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edition/$date': {
      id: '/edition/$date'
      path: '/edition/$date'
      fullPath: '/edition/$date'
      preLoaderRoute: typeof EditionDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$id.ics': {
      id: '/api/events/$id.ics'
      path: '/api/events/$id.ics'
      fullPath: '/api/events/$id.ics'
      preLoaderRoute: typeof ApiEventsIdDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AdvertiseRoute: AdvertiseRoute,
  BreakingRoute: BreakingRoute,
  CalendarRoute: CalendarRoute,
  EditionsRoute: EditionsRoute,
  ParishRoute: ParishRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsRoute: SportsRoute,
  SubscribeRoute: SubscribeRoute,
  SundayRoute: SundayRoute,
  VillageRoute: VillageRoute,
  ApiCalendarDoticsRoute: ApiCalendarDoticsRoute,
  DispatchesSlugRoute: DispatchesSlugRoute,
  EditionDateRoute: EditionDateRoute,
  DispatchesIndexRoute: DispatchesIndexRoute,
  ApiEventsIdDoticsRoute: ApiEventsIdDoticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
