/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as BreakingRouteImport } from './routes/breaking'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DispatchesRouteImport } from './routes/dispatches'
import { Route as ParishRouteImport } from './routes/parish'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as VillageRouteImport } from './routes/village'
import { Route as ApiCalendarDoticsRouteImport } from './routes/api/calendar[.]ics'
import { Route as DispatchesSlugRouteImport } from './routes/dispatches.$slug'
import { Route as ApiEventsIdDoticsRouteImport } from './routes/api/events/$id[.]ics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakingRoute = BreakingRouteImport.update({
  id: '/breaking',
  path: '/breaking',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchesRoute = DispatchesRouteImport.update({
  id: '/dispatches',
  path: '/dispatches',
  getParentRoute: () => rootRouteImport,
} as any)
const ParishRoute = ParishRouteImport.update({
  id: '/parish',
  path: '/parish',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VillageRoute = VillageRouteImport.update({
  id: '/village',
  path: '/village',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarDoticsRoute = ApiCalendarDoticsRouteImport.update({
  id: '/api/calendar.ics',
  path: '/api/calendar.ics',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchesSlugRoute = DispatchesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DispatchesRoute,
} as any)
const ApiEventsIdDoticsRoute = ApiEventsIdDoticsRouteImport.update({
  id: '/api/events/$id.ics',
  path: '/api/events/$id.ics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/breaking': typeof BreakingRoute
  '/calendar': typeof CalendarRoute
  '/dispatches': typeof DispatchesRouteWithChildren
  '/parish': typeof ParishRoute
  '/subscribe': typeof SubscribeRoute
  '/village': typeof VillageRoute
  '/api/calendar.ics': typeof ApiCalendarDoticsRoute
  '/dispatches/$slug': typeof DispatchesSlugRoute
  '/api/events/$id.ics': typeof ApiEventsIdDoticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/breaking': typeof BreakingRoute
  '/calendar': typeof CalendarRoute
  '/dispatches': typeof DispatchesRouteWithChildren
  '/parish': typeof ParishRoute
  '/subscribe': typeof SubscribeRoute
  '/village': typeof VillageRoute
  '/api/calendar.ics': typeof ApiCalendarDoticsRoute
  '/dispatches/$slug': typeof DispatchesSlugRoute
  '/api/events/$id.ics': typeof ApiEventsIdDoticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/breaking': typeof BreakingRoute
  '/calendar': typeof CalendarRoute
  '/dispatches': typeof DispatchesRouteWithChildren
  '/parish': typeof ParishRoute
  '/subscribe': typeof SubscribeRoute
  '/village': typeof VillageRoute
  '/api/calendar.ics': typeof ApiCalendarDoticsRoute
  '/dispatches/$slug': typeof DispatchesSlugRoute
  '/api/events/$id.ics': typeof ApiEventsIdDoticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/breaking'
    | '/calendar'
    | '/dispatches'
    | '/parish'
    | '/subscribe'
    | '/village'
    | '/api/calendar.ics'
    | '/dispatches/$slug'
    | '/api/events/$id.ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/breaking'
    | '/calendar'
    | '/dispatches'
    | '/parish'
    | '/subscribe'
    | '/village'
    | '/api/calendar.ics'
    | '/dispatches/$slug'
    | '/api/events/$id.ics'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/breaking'
    | '/calendar'
    | '/dispatches'
    | '/parish'
    | '/subscribe'
    | '/village'
    | '/api/calendar.ics'
    | '/dispatches/$slug'
    | '/api/events/$id.ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  BreakingRoute: typeof BreakingRoute
  CalendarRoute: typeof CalendarRoute
  DispatchesRoute: typeof DispatchesRouteWithChildren
  ParishRoute: typeof ParishRoute
  SubscribeRoute: typeof SubscribeRoute
  VillageRoute: typeof VillageRoute
  ApiCalendarDoticsRoute: typeof ApiCalendarDoticsRoute
  ApiEventsIdDoticsRoute: typeof ApiEventsIdDoticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breaking': {
      id: '/breaking'
      path: '/breaking'
      fullPath: '/breaking'
      preLoaderRoute: typeof BreakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatches': {
      id: '/dispatches'
      path: '/dispatches'
      fullPath: '/dispatches'
      preLoaderRoute: typeof DispatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parish': {
      id: '/parish'
      path: '/parish'
      fullPath: '/parish'
      preLoaderRoute: typeof ParishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/village': {
      id: '/village'
      path: '/village'
      fullPath: '/village'
      preLoaderRoute: typeof VillageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar.ics': {
      id: '/api/calendar.ics'
      path: '/api/calendar.ics'
      fullPath: '/api/calendar.ics'
      preLoaderRoute: typeof ApiCalendarDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatches/$slug': {
      id: '/dispatches/$slug'
      path: '/$slug'
      fullPath: '/dispatches/$slug'
      preLoaderRoute: typeof DispatchesSlugRouteImport
      parentRoute: typeof DispatchesRoute
    }
    '/api/events/$id.ics': {
      id: '/api/events/$id.ics'
      path: '/api/events/$id.ics'
      fullPath: '/api/events/$id.ics'
      preLoaderRoute: typeof ApiEventsIdDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DispatchesRouteChildren {
  DispatchesSlugRoute: typeof DispatchesSlugRoute
}

const DispatchesRouteChildren: DispatchesRouteChildren = {
  DispatchesSlugRoute: DispatchesSlugRoute,
}

const DispatchesRouteWithChildren = DispatchesRoute._addFileChildren(
  DispatchesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  BreakingRoute: BreakingRoute,
  CalendarRoute: CalendarRoute,
  DispatchesRoute: DispatchesRouteWithChildren,
  ParishRoute: ParishRoute,
  SubscribeRoute: SubscribeRoute,
  VillageRoute: VillageRoute,
  ApiCalendarDoticsRoute: ApiCalendarDoticsRoute,
  ApiEventsIdDoticsRoute: ApiEventsIdDoticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
